name: zhihu_zhuan_lan
description: 知乎专栏flutter版

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  http: ^0.11.3+16
  transparent_image: ^0.1.0
  flutter_webview_plugin: ^0.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/image/icon_splash.jpg

