name: flutter_banner_widget
description: banner widget
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  transparent_image: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/image/banner1.jpg
    - lib/image/banner2.jpg
    - lib/image/banner3.png
    - lib/image/banner4.jpg
