name: flutter_codekk
description: codekk flutter
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  http: ^0.11.3+16
  transparent_image: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
