name: flutter_codekk
description: codekk flutter
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  http: ^0.11.3+16
  json_serializable: ^1.5.1
  build_runner: ^1.0.0
  flutter_webview_plugin: ^0.2.1+2
  shared_preferences: ^0.4.3
  url_launcher: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/image/icon_example.jpg