name: flutter_ipanda
description: iPanda
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  http: ^0.11.3+16
  json_serializable: ^0.5.0
  build_runner: ^0.8.9
  flutter_webview_plugin: ^0.1.5
  shared_preferences: ^0.4.1
  url_launcher: ^3.0.0
  video_player: ^0.5.3
  flutter_banner_widget:
      path: ../flutter_banner_widget
  flutter_tab_widget:
      path: ../flutter_tab_widget
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
