name: flutter_tab_widget
description: A new Flutter tab.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
